feat(devops): pre-commit db ts gen support

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -8,3 +8,10 @@ if git diff --cached --name-only | grep -q '^apps/web/'; then
   # echo "🟡 Check test errors if any."
   # cd apps/web && bun test
 fi
+if git diff --cached --name-only | grep -q '^services/supabase/'; then
+  echo "🔵 Running Supabase Typescript generation."
+  if ! cd services/supabase || ! bun gen; then
+    echo "🔴 Failed to run Supabase TypeScript generation. Make sure if you are locally running! 👀"
+    exit 1
+  fi
+fi
